### ISSUE TITLE
OSError: [Errno 28] inotify watch limit reached

### ISSUE THREAD

**Issue by micahflee** [micahflee/org.onionshare.OnionShare#4]
```
$ flatpak run org.onionshare.OnionShare
OnionShare 2.2 | https://onionshare.org/
Gtk-Message: 19:06:44.970: Failed to load module "pantheon-filechooser-module"
Gtk-Message: 19:06:44.997: Failed to load module "canberra-gtk-module"
Gtk-Message: 19:06:44.997: Failed to load module "canberra-gtk-module"
QIBusPlatformInputContext: invalid portal bus.
Qt: Session management error: None of the authentication protocols specified are supported
QApplication: invalid style override 'adwaita' passed, ignoring it.
	Available styles: Breeze, Windows, Fusion
Traceback (most recent call last):
  File "/app/bin/onionshare-gui", line 22, in <module>
    onionshare_gui.main()
  File "/app/lib/python3.7/site-packages/onionshare_gui/__init__.py", line 163, in main
    main_window = MainWindow(common, filenames)
  File "/app/lib/python3.7/site-packages/onionshare_gui/main_window.py", line 121, in __init__
    self.tabs = TabWidget(self.common, self.system_tray, self.status_bar)
  File "/app/lib/python3.7/site-packages/onionshare_gui/tab_widget.py", line 80, in __init__
    self.observer.start()
  File "/app/lib/python3.7/site-packages/watchdog/observers/api.py", line 253, in start
    emitter.start()
  File "/app/lib/python3.7/site-packages/watchdog/utils/__init__.py", line 110, in start
    self.on_thread_start()
  File "/app/lib/python3.7/site-packages/watchdog/observers/inotify.py", line 121, in on_thread_start
    self._inotify = InotifyBuffer(path, self.watch.is_recursive)
  File "/app/lib/python3.7/site-packages/watchdog/observers/inotify_buffer.py", line 35, in __init__
    self._inotify = Inotify(path, recursive)
  File "/app/lib/python3.7/site-packages/watchdog/observers/inotify_c.py", line 200, in __init__
    self._add_dir_watch(path, recursive, event_mask)
  File "/app/lib/python3.7/site-packages/watchdog/observers/inotify_c.py", line 388, in _add_dir_watch
    self._add_watch(path, mask)
  File "/app/lib/python3.7/site-packages/watchdog/observers/inotify_c.py", line 409, in _add_watch
    Inotify._raise_error()
  File "/app/lib/python3.7/site-packages/watchdog/observers/inotify_c.py", line 421, in _raise_error
    raise OSError(errno.ENOSPC, "inotify watch limit reached")
OSError: [Errno 28] inotify watch limit reached
```

**Comment by micahflee** [comment]
Fixed by removing watchdog as a dependency
